spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
         uri: https://github.com/yuzhangxiao/config-repo-demo.git
         username: yuzhangxiao
         password: 9689389924zY
server:
  port: 1201